/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution
{
public:
  char findTheDifference(string s, string t)
  {
    while (t.size() > 1)
  	{
  		auto i = t[0];
  		string::iterator it = find(s.begin(), s.end(), i);
  		if (it == s.end())
  		{
  			return i;
  		}
  		else
  		{
  			t.erase(t.begin(), t.begin() + 1);
        s.erase(it, it + 1);
  		}
  	}
    return t[0];
    //runtime: 8ms?
  }
};
